#!/bin/bash

# $1 project directory
# $2 output iso name

xorriso \
    -as mkisofs \
    -iso-level 3 \
    -full-iso9660-filenames \
    -volid "CUSTOM" \
    -eltorito-alt-boot \
        -e EFI/efiboot.img \
        -no-emul-boot \
    -append_partition 2 0xef $1/scratch/efiboot.img \
    -output "$2" \
    -graft-points \
        "$1/image" \
        /EFI/efiboot.img=$1/scratch/efiboot.img
